version: '3.8'

services:
  # 後端服務
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: attendance_backend
    ports:
      - "8080:8080"
    environment:
      # PostgreSQL 資料庫配置
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=attendance_db
      - PGUSER=attendance_user
      - PGPASSWORD=attendance_password
      - PORT=8080
    depends_on:
      - db
    networks:
      - attendance_network
    restart: unless-stopped

  # 前端服務
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: attendance_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - attendance_network
    restart: unless-stopped

  # PostgreSQL 資料庫
  db:
    image: postgres:15-alpine
    container_name: attendance_db
    environment:
      - POSTGRES_DB=attendance_db
      - POSTGRES_USER=attendance_user
      - POSTGRES_PASSWORD=attendance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - attendance_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  attendance_network:
    driver: bridge
