# Frontend configuration
[phases.setup]
nixPkgs = ["nodejs-18_x", "pnpm"]

[phases.install]
cmds = ["cd frontend && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd frontend && pnpm run build"]

[start]
cmd = "cd frontend && pnpm run preview --host 0.0.0.0 --port $PORT"
