# Backend service configuration
[build]
builder = "nixpacks"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar backend/target/backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/employees/getall"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
