version: 2

environments:
  production:
    variables:
      NODE_ENV: production
      PORT: ${{PORT}}
      DATABASE_URL: ${{DATABASE_URL}}
      PGHOST: ${{PGHOST}}
      PGPORT: ${{PGPORT}}
      PGDATABASE: ${{PGDATABASE}}
      PGUSER: ${{PGUSER}}
      PGPASSWORD: ${{PGPASSWORD}}
      
build:
  commands:
    - echo "Building backend with Maven..."
  
deploy:
  startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
  healthcheckPath: "/health"
  
services:
  backend:
    source: ./backend
    build:
      commands:
        - "./mvnw clean package -DskipTests"
    deploy:
      startCommand: "java -Dserver.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar"
